Include SESE.idl

Export
Constraint IfThenElseBranch
  ( {condjump} strictly control flow dominates {then.end} and
  {condjump} strictly control flow dominates {else.end} and
# Make sure the start is actually the start and not the instructions
# before it.
  {then.start} is first successor of {condjump} and
  {else.start} is second successor of {condjump} and
# Not sure I need this.
  {then.start} spans block to {then.end} and
  {else.start} spans block to {else.end} and
# Make sure these are the end of the branch? (Might duplicate the above)
  {then.end} has control flow to {endif} and 
  {else.end} has control flow to {endif}
  )
End

Export
Constraint Loop
  ( {top} control flow dominates {end} and
  {top} is first successor of {end} )
End

Export
Constraint IfThenBranch
  ({condjump} strictly control flow dominates {then.end} and
  {condjump} has control flow to {then.start} and
  {then.start} spans block to {then.end} and
  {then.end} has control flow to {endif} and
  {condjump} has control flow to {endif}
)
End
